services:
  llm_chatbot:
    build: .
    container_name: llm_chatbot
    environment:
      DATABASE_URL: $DATABASE_URL
      TEST_DATABASE_URL: $TEST_DATABASE_URL
      WEBHOOK_VERIFY_TOKEN: $WEBHOOK_VERIFY_TOKEN
      GRAPH_API_TOKEN: $GRAPH_API_TOKEN
      OLLAMA_HOST: $OLLAMA_HOST
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_BASE_URL: $OPENAI_BASE_URL
      AI_SERVICE: $AI_SERVICE
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - containers
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  containers:
    external: true
