# fly.toml app configuration file generated for llm-chatbot on 2025-02-27T09:34:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llm-chatbot'
primary_region = 'gru'

[build]

[deploy]
release_command = 'npm run db:setup'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = '256mb'
